# Generated by Django 5.1.15 on 2026-03-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='puede_cerrar_caja',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
