# Generated by Django 5.1.15 on 2026-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_puede_cerrar_caja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='calle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='zona',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
