# Generated by Django 5.1.15 on 2026-03-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0002_remove_gasto_creado_alter_gasto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
