# Generated by Django 5.1.15 on 2026-03-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_venta_uusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='uusuario',
            new_name='usuario',
        ),
    ]
