# Generated by Django 5.1.15 on 2026-03-04 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.venta'),
        ),
    ]
