# Generated by Django 5.1.15 on 2026-03-05 16:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_caja_venta'),
        ('venta', '0002_venta_uusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='tipo',
            field=models.CharField(choices=[('APERTURA', 'Apertura de Caja'), ('CIERRE', 'Cierre de Caja'), ('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='caja',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.venta'),
        ),
    ]
