# Generated by Django 5.1.15 on 2026-03-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_turnocaja_caja_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=20),
        ),
    ]
